language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t thecosmicsound/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thecosmicsound/react-test npm test

after_success:
  - docker build -t thecosmicsound/multi-client ./client
  - docker build -t thecosmicsound/multi-nginx ./nginx
  - docker build -t thecosmicsound/multi-server ./server
  - docker build -t thecosmicsound/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push thecosmicsound/multi-client
  - docker push thecosmicsound/multi-nginx
  - docker push thecosmicsound/multi-server
  - docker push thecosmicsound/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-549051294676"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
